export const ProjectsMeta = [
  {
    id: 0,
    imageUrl: 'https://avatars.githubusercontent.com/u/102288397?v=4',
    title: 'radiohead',
    subTitle: 'paranoid android',
    projectDeadline: '2024-10-21',
    maxProjectMembers: 5,
    currentProjectMembers: 1,
    viewCount: 100,
    heartCount: 10,
  },
  {
    id: 1,
    title: 'radiohead',
    subTitle: 'paranoid android',
    projectDeadline: '2024-10-21',
    maxProjectMembers: 5,
    currentProjectMembers: 1,
    viewCount: 100,
    heartCount: 10,
  },
  {
    id: 2,
    title: 'radiohead',
    subTitle:
      'paranoid android paranoid android paranoid android paranoid android paranoid android paranoid android',
    projectDeadline: '2024-10-21',
    maxProjectMembers: 5,
    currentProjectMembers: 1,
    viewCount: 100,
    heartCount: 10,
  },
  {
    id: 3,
    title: 'radiohead',
    subTitle: 'paranoid android',
    projectDeadline: '2024-10-21',
    maxProjectMembers: 5,
    currentProjectMembers: 1,
    viewCount: 100,
    heartCount: 10,
  },
  {
    id: 4,
    title: 'radiohead',
    subTitle: 'paranoid android',
    projectDeadline: '2024-10-21',
    maxProjectMembers: 5,
    currentProjectMembers: 1,
    viewCount: 100,
    heartCount: 10,
  },
  {
    id: 5,
    title: 'radiohead',
    subTitle: 'paranoid android',
    projectDeadline: '2024-10-21',
    maxProjectMembers: 5,
    currentProjectMembers: 1,
    viewCount: 100,
    heartCount: 10,
  },
];
